build:
	gcc main.c -o main.out
	gcc Mars_Station.h -o Mars_Station.out
	gcc Rovers/Rover.h -o Rover.out
	gcc Rovers/Normal_Rovers.h -o Normal_Rovers.out
	gcc Rovers/Digging_Rovers.h -o Digging_Rovers.out
	gcc Rovers/polar_Rovers.h -o polar_Rovers.out
	gcc Request/Request.h -o Request.out
	gcc Request/New_Request.h -o New_Request.out
	gcc ADT/ArrayStack.h -o ArrayStack.out
	gcc ADT/LinkedQueue.h -o LinkedQueue.out
	gcc ADT/priQueue.h -o priQueue.out
clean:
	rm -f *.out
all:
	make clean
	make build
run:
	./main.out
